export const STORE_URLS = [
  "https://www.shopstitchstories.com/collections/tops-shirts",
  // "https://saralhome.com/collections/bedsheet",
  // "https://www.amydus.com/collections/plus-size-jeans",
  // "https://www.nicobar.com/collections/sindhu?filter.p.m.filter.collection_category=Men&filter.v.availability=1&sort_by=manual&test=1&view=cc",
  // "https://hiutdenim.co.uk/collections/mens",
  // "https://www.nicobar.com/collections/sindhu?view=cc",
  // "https://www.tentree.com/collections/womens?page=1",
  // "https://maguireshoes.com/collections/flats",
  // "https://kirrinfinch.com/collections/all-pants",
];

export const VARIANT_CANDIDATES = [
  "a",
  "label",
  'input[type="radio"]',
  "select",
  "div[data-id]",
  "div[data-value]",
  "div[data-variantid]",
  "div[data-available]",
  "div[data-variant]",
  'div[role="button"]',
  'div[role="listbox"]',
  'div[role="combobox"]',
  '[class*="swatch"]',
  '[class*="variant"]',
];

export const NAVBAR_CANDIDATES = [
  "header",
  "footer",
  "nav",
  "[role='navigation']",
  ".header",
  ".site-header",
  ".main-header",
  ".navbar",
  ".nav",
  ".top-nav",
  ".navigation",
  ".nav-bar",
  ".nav-wrapper",
  ".header-wrapper",
  ".shopify-section-header",
  ".header__inline-menu",
  ".header__menu",
  ".header__navigation",
  ".menu-drawer",
  ".menu__drawer",
  ".menu__dropdown",
  ".menu__list",
  ".menu__item",
  ".drawer",
  ".drawer__content",
  "[aria-label*='menu']",
  "[aria-label*='navigation']",
  "[aria-label*='nav']",
];
